src/spaceone/plugin/info/common_info.py

Add total_count to StatisticsQuery result

---

Dockerfile
src/spaceone/plugin/conf/proto_conf.py

Change proto conf path and run command

---

src/spaceone/plugin/service/supervisor_service.py

Remove only required parameter

---

src/spaceone/plugin/info/plugin_info.py
src/spaceone/plugin/manager/plugin_manager/__init__.py
src/spaceone/plugin/service/supervisor_service.py

Signed-off-by: Choonho Son <choonhoson@megazone.com>

list endpoints

---

src/spaceone/plugin/model/installed_plugin_model.py
src/spaceone/plugin/model/installed_plugin_ref_model.py
src/spaceone/plugin/model/supervisor_model.py

Signed-off-by: Choonho Son <choonhoson@megazone.com>

Add db index

---

src/spaceone/plugin/error/plugin.py
src/spaceone/plugin/manager/plugin_manager/__init__.py
src/spaceone/plugin/manager/plugin_manager/plugin_ref_manager.py
src/spaceone/plugin/model/installed_plugin_model.py
src/spaceone/plugin/model/installed_plugin_ref_model.py
src/spaceone/plugin/service/plugin_service.py

Sometime, there was multiple plugins.
This is caused by multiple request simultaneously.

Fix install plugin error

---

src/spaceone/plugin/model/installed_plugin_model.py

Add unique_with plugin_id, version, supervisor_id

Fix plugin creation

---

src/spaceone/plugin/connector/repository_connector.py
src/spaceone/plugin/error/plugin.py
src/spaceone/plugin/manager/__init__.py
src/spaceone/plugin/manager/plugin_manager/__init__.py
src/spaceone/plugin/manager/repository_manager.py
src/spaceone/plugin/service/plugin_service.py

If get_plugin_endpoint was first call, endpoint was NONE.

Fix get_plugin_endpoint

---

src/spaceone/plugin/info/plugin_info.py
src/spaceone/plugin/info/supervisor_info.py
src/spaceone/plugin/model/installed_plugin_model.py
src/spaceone/plugin/model/installed_plugin_ref_model.py
src/spaceone/plugin/model/supervisor_model.py
src/spaceone/plugin/model/supervisor_ref_model.py
src/spaceone/plugin/service/supervisor_service.py

Change tags field format

---

src/spaceone/plugin/service/supervisor_service.py

Change tag search spec

---

src/spaceone/plugin/info/supervisor_info.py

Bug fix: supervisor tag null issue

---

src/spaceone/plugin/info/supervisor_info.py
src/spaceone/plugin/service/supervisor_service.py

add debug code

---

src/spaceone/plugin/info/supervisor_info.py
src/spaceone/plugin/service/supervisor_service.py

Remove debug code

---

release_notes/version_1.5.3.md
src/spaceone/plugin/info/plugin_info.py
src/spaceone/plugin/manager/plugin_manager/__init__.py
src/spaceone/plugin/manager/plugin_manager/plugin_state.py
src/spaceone/plugin/service/supervisor_service.py

Support recover-plugin API

---

docs/plugin-scheduler.md
pkg/pip_requirements.txt
release_notes/version_1.5.3.md
src/setup.py
src/spaceone/plugin/conf/global_conf.py
src/spaceone/plugin/connector/__init__.py
src/spaceone/plugin/connector/identity_connector.py
src/spaceone/plugin/manager/__init__.py
src/spaceone/plugin/manager/identity_manager.py
src/spaceone/plugin/manager/plugin_manager/__init__.py
src/spaceone/plugin/manager/plugin_manager/plugin_ref_manager.py
src/spaceone/plugin/scheduler/cleanup_scheduler.py
src/spaceone/plugin/service/supervisor_service.py

Add plugin clean-up scheduler

---

src/spaceone/plugin/api/v1/supervisor.py
src/spaceone/plugin/conf/global_conf.py
src/spaceone/plugin/service/plugin_service.py
src/spaceone/plugin/service/supervisor_service.py

Add RBAC features

---

src/spaceone/plugin/service/plugin_service.py
src/spaceone/plugin/service/supervisor_service.py

Add mutation handler to plugin and supervisor service

---

src/spaceone/plugin/connector/repository_connector.py

Fix a get_plugin error

---

src/spaceone/plugin/service/plugin_service.py

Exclude auth (get_plugin_endpoint)

---

src/spaceone/plugin/scheduler/cleanup_scheduler.py

- service
- resource
- verb
- authorization
- mutation

Add metadata for RBAC

---

src/spaceone/plugin/info/supervisor_info.py
src/spaceone/plugin/service/supervisor_service.py

Change grpc timestamp type to string type(iso8601)

Change tags message type

---

src/spaceone/plugin/info/supervisor_info.py

Fix import bug

---

src/spaceone/plugin/conf/global_conf.py

Change local cache ttl

---

src/spaceone/plugin/manager/plugin_manager/__init__.py
src/spaceone/plugin/service/plugin_service.py

fix: fix a argument bug

---

src/spaceone/plugin/connector/repository_connector.py
src/spaceone/plugin/manager/plugin_manager/__init__.py
src/spaceone/plugin/manager/plugin_manager/plugin_ref_manager.py
src/spaceone/plugin/manager/repository_manager.py
src/spaceone/plugin/service/plugin_service.py
src/spaceone/plugin/service/supervisor_service.py

feat: add plugin upgrade feature

---

src/spaceone/plugin/manager/plugin_manager/__init__.py

refactor: reduce plugin provisioning wait time

---

src/spaceone/plugin/conf/global_conf.py

refactor: remove unused configuration

---

src/spaceone/plugin/manager/supervisor_manager/__init__.py

fix: fix typo

---

src/spaceone/plugin/manager/plugin_manager/__init__.py
src/spaceone/plugin/manager/supervisor_manager/__init__.py

fix: fix supervisor deregister error

---

src/spaceone/plugin/model/supervisor_model.py

add tags in updatable fields in supervisor model
tag update does not work. (supervisor) (#50)

add tags in updatable fields in supervisor model
